apiVersion: k6.grafana.o.crossplane.io/v1alpha1
kind: ProjectAllowedLoadZones
metadata:
  name: example-projectallowedloadzones
  namespace: default
spec:
  forProvider:
    projectID: "example-project_id"
  providerConfigRef:
    name: example
