apiVersion: sm.grafana.crossplane.io/v1alpha1
kind: Check
metadata:
  annotations:
    meta.upbound.io/example-id: sm/v1alpha1/check
  labels:
    testing.upbound.io/example-name: dns
  name: dns
spec:
  forProvider:
    enabled: false
    job: DNS Defaults
    labels:
      foo: bar
    probes:
    - ${data.grafana_synthetic_monitoring_probes.main.probes.Ohio}
    settings:
    - dns:
      - {}
    target: grafana.com
