apiVersion: oncall.grafana.m.crossplane.io/v1alpha1
kind: Route
metadata:
  annotations:
    meta.upbound.io/example-id: oncall/v1alpha1/route
  labels:
    testing.upbound.io/example-name: example_route
  name: example-route
  namespace: upbound-system
spec:
  forProvider:
    escalationChainSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    integrationSelector:
      matchLabels:
        testing.upbound.io/example-name: example_integration
    msteams:
    - enabled: false
      id: ONCALLMSTEAMSID
    position: 0
    routingRegex: us-(east|west)
    slack:
    - channelId: ${data.grafana_oncall_slack_channel.example_slack_channel.slack_id}
      enabled: true
    telegram:
    - enabled: true
      id: ONCALLTELEGRAMID

---

apiVersion: oncall.grafana.m.crossplane.io/v1alpha1
kind: EscalationChain
metadata:
  annotations:
    meta.upbound.io/example-id: oncall/v1alpha1/route
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: upbound-system
spec:
  forProvider:
    name: default

---

apiVersion: oncall.grafana.m.crossplane.io/v1alpha1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: oncall/v1alpha1/route
  labels:
    testing.upbound.io/example-name: example_integration
  name: example-integration
  namespace: upbound-system
spec:
  forProvider:
    defaultRoute:
    - {}
    name: Grafana Integration
    type: grafana
