apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccountToken
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccounttoken
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: key_foo
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: example
