apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/team
  labels:
    testing.upbound.io/example-name: test-team
  name: test-team
spec:
  forProvider:
    email: teamemail@example.com
    memberRefs:
    - name: example
    name: Test Team
