apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/team
  labels:
    testing.upbound.io/example-name: test-team
  name: test-team
spec:
  forProvider:
    email: teamemail@example.com
    memberRefs:
    - name: viewer
    name: Test Team

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/team
  labels:
    testing.upbound.io/example-name: viewer
  name: viewer
spec:
  forProvider:
    email: viewer@example.com
    login: viewer
    name: Viewer
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
