apiVersion: cloud.grafana.m.crossplane.io/v1alpha1
kind: PluginInstallation
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/plugininstallation
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    cloudStackSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    slug: some-plugin
    version: 1.2.3
