apiVersion: oss.grafana.o.crossplane.io/v1alpha1
kind: LibraryPanelSet
metadata:
  name: example-librarypanelset
  namespace: default
spec:
  forProvider:
    orgID: "example-org_id"
  providerConfigRef:
    name: example
