apiVersion: oss.grafana.o.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-serviceaccount
  namespace: default
spec:
  forProvider:
    name: "example-name"
    orgID: "example-org_id"
  providerConfigRef:
    name: example
