version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - zerologlint
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - shadow
    lll:
      tab-width: 1
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
    unused:
      exported-fields-are-used: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - scopelint
          - unparam
        path: _test(ing)?\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gocritic
        text: '(hugeParam|rangeValCopy):'
      - linters:
          - staticcheck
        text: 'SA3000:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
    paths:
      - zz_\..+\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/upbound/upjet-provider-template
  exclusions:
    generated: lax
    paths:
      - zz_\..+\.go$
      - third_party$
      - builtin$
      - examples$
