apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/organization
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    adminRefs:
    - name: example
    adminUserSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    createUsers: true
    editorRefs:
    - name: example
    - name: example
    name: Test Organization
    viewerRefs:
    - name: example
    - name: example
