apiVersion: oncall.grafana.crossplane.io/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: oncall/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: example_schedule
  name: example-schedule
spec:
  forProvider:
    icalUrlOverrides: https://example.com/example_overrides_ical.ics
    icalUrlPrimary: https://example.com/example_ical.ics
    name: Example Ical Schedule
    slack:
    - slackChannelSelector:
        matchLabels:
          testing.upbound.io/example-name: grafana_oncall_slack_channel
      slackUserGroupSelector:
        matchLabels:
          testing.upbound.io/example-name: grafana_oncall_user_group
    teamSelector:
      matchLabels:
        testing.upbound.io/example-name: grafana_oncall_team
    type: ical
