apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: FolderPermission
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folderpermission
  labels:
    testing.upbound.io/example-name: collectionPermission
  name: collectionpermission
  namespace: upbound-system
spec:
  forProvider:
    folderSelector:
      matchLabels:
        testing.upbound.io/example-name: collection
    permissions:
    - permission: Edit
      role: Editor
    - permission: View
      teamSelector:
        matchLabels:
          testing.upbound.io/example-name: team
    - permission: Admin
      userSelector:
        matchLabels:
          testing.upbound.io/example-name: user

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folderpermission
  labels:
    testing.upbound.io/example-name: collection
  name: collection
  namespace: upbound-system
spec:
  forProvider:
    title: Folder Title

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folderpermission
  labels:
    testing.upbound.io/example-name: team
  name: team
  namespace: upbound-system
spec:
  forProvider:
    name: Team Name

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folderpermission
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: upbound-system
spec:
  forProvider:
    email: user.name@example.com
    login: user.name
    passwordSecretRef:
      key: example-key
      name: example-secret
