apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: ServiceAccountPermissionItem
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermissionitem
  labels:
    testing.upbound.io/example-name: on_team
  name: on-team
  namespace: upbound-system
spec:
  forProvider:
    permission: Admin
    serviceAccountId: ${grafana_service_account.test.id}
    team: ${grafana_team.team.id}

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermissionitem
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    isDisabled: false
    name: terraform-sa
    role: Editor

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermissionitem
  labels:
    testing.upbound.io/example-name: team
  name: team
  namespace: upbound-system
spec:
  forProvider:
    name: Team Name

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermissionitem
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: upbound-system
spec:
  forProvider:
    email: user.name@example.com
    login: user.name
    passwordSecretRef:
      key: example-key
      name: example-secret
