/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package fleetmanagement

import (
	"context"
	"strconv"

	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	v1alpha1 "github.com/grafana/crossplane-provider-grafana/v2/apis/observed/fleetmanagement/v1alpha1"
	tfdatasource "github.com/grafana/crossplane-provider-grafana/v2/pkg/tfdatasource"
)

var CollectorSpec = tfdatasource.Spec{
	DataSourceName: "grafana_fleet_management_collector",
	ManagedKind:    v1alpha1.Collector_GroupVersionKind,
	NewManaged:     func() resource.Managed { return &v1alpha1.Collector{} },
	Read: tfdatasource.NewFrameworkReadFn(
		newDSCollector,
		func(_ resource.Managed) map[string]tftypes.Value {
			return nil
		},
		func(ctx context.Context, mg resource.Managed, state tfsdk.State) {
			cr := mg.(*v1alpha1.Collector)
			{
				var v *string
				if diags := state.GetAttribute(ctx, path.Root("collector_type"), &v); !diags.HasError() && v != nil {
					cr.Status.AtProvider.CollectorType = v
				}
			}
			{
				var v *bool
				if diags := state.GetAttribute(ctx, path.Root("enabled"), &v); !diags.HasError() && v != nil {
					cr.Status.AtProvider.Enabled = v
				}
			}
			// TODO: complex type map[string]string for local_attributes
			// TODO: complex type map[string]string for remote_attributes
		},
	),
	ConnectionDetailsFn: func(mg resource.Managed) managed.ConnectionDetails {
		cr := mg.(*v1alpha1.Collector)
		cd := managed.ConnectionDetails{}
		if id := meta.GetExternalName(cr); id != "" {
			cd["id"] = []byte(id)
		}
		if cr.Status.AtProvider.CollectorType != nil {
			cd["collector_type"] = []byte(*cr.Status.AtProvider.CollectorType)
		}
		if cr.Status.AtProvider.Enabled != nil {
			cd["enabled"] = []byte(strconv.FormatBool(*cr.Status.AtProvider.Enabled))
		}
		return cd
	},
}
