//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOs) DeepCopyInto(out *SLOs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOs.
func (in *SLOs) DeepCopy() *SLOs {
	if in == nil {
		return nil
	}
	out := new(SLOs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLOs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsList) DeepCopyInto(out *SLOsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SLOs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsList.
func (in *SLOsList) DeepCopy() *SLOsList {
	if in == nil {
		return nil
	}
	out := new(SLOsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SLOsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsObservation) DeepCopyInto(out *SLOsObservation) {
	*out = *in
	if in.SLOs != nil {
		in, out := &in.SLOs, &out.SLOs
		*out = make([]SLOsSLOs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsObservation.
func (in *SLOsObservation) DeepCopy() *SLOsObservation {
	if in == nil {
		return nil
	}
	out := new(SLOsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsParameters) DeepCopyInto(out *SLOsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsParameters.
func (in *SLOsParameters) DeepCopy() *SLOsParameters {
	if in == nil {
		return nil
	}
	out := new(SLOsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOs) DeepCopyInto(out *SLOsSLOs) {
	*out = *in
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = make([]SLOsSLOsAlerting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DestinationDatasource != nil {
		in, out := &in.DestinationDatasource, &out.DestinationDatasource
		*out = make([]SLOsSLOsDestinationDatasource, len(*in))
		copy(*out, *in)
	}
	if in.FolderUID != nil {
		in, out := &in.FolderUID, &out.FolderUID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]SLOsSLOsLabel, len(*in))
		copy(*out, *in)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]SLOsSLOsObjectives, len(*in))
		copy(*out, *in)
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = make([]SLOsSLOsQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchExpression != nil {
		in, out := &in.SearchExpression, &out.SearchExpression
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOs.
func (in *SLOsSLOs) DeepCopy() *SLOsSLOs {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlerting) DeepCopyInto(out *SLOsSLOsAlerting) {
	*out = *in
	if in.AdvancedOptions != nil {
		in, out := &in.AdvancedOptions, &out.AdvancedOptions
		*out = make([]SLOsSLOsAlertingAdvancedOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = make([]SLOsSLOsAlertingAnnotation, len(*in))
		copy(*out, *in)
	}
	if in.Fastburn != nil {
		in, out := &in.Fastburn, &out.Fastburn
		*out = make([]SLOsSLOsAlertingFastburn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]SLOsSLOsAlertingLabel, len(*in))
		copy(*out, *in)
	}
	if in.Slowburn != nil {
		in, out := &in.Slowburn, &out.Slowburn
		*out = make([]SLOsSLOsAlertingSlowburn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlerting.
func (in *SLOsSLOsAlerting) DeepCopy() *SLOsSLOsAlerting {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlerting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingAdvancedOptions) DeepCopyInto(out *SLOsSLOsAlertingAdvancedOptions) {
	*out = *in
	if in.MinFailures != nil {
		in, out := &in.MinFailures, &out.MinFailures
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingAdvancedOptions.
func (in *SLOsSLOsAlertingAdvancedOptions) DeepCopy() *SLOsSLOsAlertingAdvancedOptions {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingAdvancedOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingAnnotation) DeepCopyInto(out *SLOsSLOsAlertingAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingAnnotation.
func (in *SLOsSLOsAlertingAnnotation) DeepCopy() *SLOsSLOsAlertingAnnotation {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingFastburn) DeepCopyInto(out *SLOsSLOsAlertingFastburn) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = make([]SLOsSLOsAlertingFastburnAnnotation, len(*in))
		copy(*out, *in)
	}
	if in.Enrichment != nil {
		in, out := &in.Enrichment, &out.Enrichment
		*out = make([]SLOsSLOsAlertingFastburnEnrichment, len(*in))
		copy(*out, *in)
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]SLOsSLOsAlertingFastburnLabel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingFastburn.
func (in *SLOsSLOsAlertingFastburn) DeepCopy() *SLOsSLOsAlertingFastburn {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingFastburn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingFastburnAnnotation) DeepCopyInto(out *SLOsSLOsAlertingFastburnAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingFastburnAnnotation.
func (in *SLOsSLOsAlertingFastburnAnnotation) DeepCopy() *SLOsSLOsAlertingFastburnAnnotation {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingFastburnAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingFastburnEnrichment) DeepCopyInto(out *SLOsSLOsAlertingFastburnEnrichment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingFastburnEnrichment.
func (in *SLOsSLOsAlertingFastburnEnrichment) DeepCopy() *SLOsSLOsAlertingFastburnEnrichment {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingFastburnEnrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingFastburnLabel) DeepCopyInto(out *SLOsSLOsAlertingFastburnLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingFastburnLabel.
func (in *SLOsSLOsAlertingFastburnLabel) DeepCopy() *SLOsSLOsAlertingFastburnLabel {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingFastburnLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingLabel) DeepCopyInto(out *SLOsSLOsAlertingLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingLabel.
func (in *SLOsSLOsAlertingLabel) DeepCopy() *SLOsSLOsAlertingLabel {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingSlowburn) DeepCopyInto(out *SLOsSLOsAlertingSlowburn) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = make([]SLOsSLOsAlertingSlowburnAnnotation, len(*in))
		copy(*out, *in)
	}
	if in.Enrichment != nil {
		in, out := &in.Enrichment, &out.Enrichment
		*out = make([]SLOsSLOsAlertingSlowburnEnrichment, len(*in))
		copy(*out, *in)
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = make([]SLOsSLOsAlertingSlowburnLabel, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingSlowburn.
func (in *SLOsSLOsAlertingSlowburn) DeepCopy() *SLOsSLOsAlertingSlowburn {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingSlowburn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingSlowburnAnnotation) DeepCopyInto(out *SLOsSLOsAlertingSlowburnAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingSlowburnAnnotation.
func (in *SLOsSLOsAlertingSlowburnAnnotation) DeepCopy() *SLOsSLOsAlertingSlowburnAnnotation {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingSlowburnAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingSlowburnEnrichment) DeepCopyInto(out *SLOsSLOsAlertingSlowburnEnrichment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingSlowburnEnrichment.
func (in *SLOsSLOsAlertingSlowburnEnrichment) DeepCopy() *SLOsSLOsAlertingSlowburnEnrichment {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingSlowburnEnrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsAlertingSlowburnLabel) DeepCopyInto(out *SLOsSLOsAlertingSlowburnLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsAlertingSlowburnLabel.
func (in *SLOsSLOsAlertingSlowburnLabel) DeepCopy() *SLOsSLOsAlertingSlowburnLabel {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsAlertingSlowburnLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsDestinationDatasource) DeepCopyInto(out *SLOsSLOsDestinationDatasource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsDestinationDatasource.
func (in *SLOsSLOsDestinationDatasource) DeepCopy() *SLOsSLOsDestinationDatasource {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsDestinationDatasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsLabel) DeepCopyInto(out *SLOsSLOsLabel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsLabel.
func (in *SLOsSLOsLabel) DeepCopy() *SLOsSLOsLabel {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsLabel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsObjectives) DeepCopyInto(out *SLOsSLOsObjectives) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsObjectives.
func (in *SLOsSLOsObjectives) DeepCopy() *SLOsSLOsObjectives {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsObjectives)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsQuery) DeepCopyInto(out *SLOsSLOsQuery) {
	*out = *in
	if in.Freeform != nil {
		in, out := &in.Freeform, &out.Freeform
		*out = make([]SLOsSLOsQueryFreeform, len(*in))
		copy(*out, *in)
	}
	if in.GrafanaQueries != nil {
		in, out := &in.GrafanaQueries, &out.GrafanaQueries
		*out = make([]SLOsSLOsQueryGrafanaQueries, len(*in))
		copy(*out, *in)
	}
	if in.Ratio != nil {
		in, out := &in.Ratio, &out.Ratio
		*out = make([]SLOsSLOsQueryRatio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsQuery.
func (in *SLOsSLOsQuery) DeepCopy() *SLOsSLOsQuery {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsQueryFreeform) DeepCopyInto(out *SLOsSLOsQueryFreeform) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsQueryFreeform.
func (in *SLOsSLOsQueryFreeform) DeepCopy() *SLOsSLOsQueryFreeform {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsQueryFreeform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsQueryGrafanaQueries) DeepCopyInto(out *SLOsSLOsQueryGrafanaQueries) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsQueryGrafanaQueries.
func (in *SLOsSLOsQueryGrafanaQueries) DeepCopy() *SLOsSLOsQueryGrafanaQueries {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsQueryGrafanaQueries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSLOsQueryRatio) DeepCopyInto(out *SLOsSLOsQueryRatio) {
	*out = *in
	if in.GroupByLabels != nil {
		in, out := &in.GroupByLabels, &out.GroupByLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSLOsQueryRatio.
func (in *SLOsSLOsQueryRatio) DeepCopy() *SLOsSLOsQueryRatio {
	if in == nil {
		return nil
	}
	out := new(SLOsSLOsQueryRatio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsSpec) DeepCopyInto(out *SLOsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsSpec.
func (in *SLOsSpec) DeepCopy() *SLOsSpec {
	if in == nil {
		return nil
	}
	out := new(SLOsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOsStatus) DeepCopyInto(out *SLOsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOsStatus.
func (in *SLOsStatus) DeepCopy() *SLOsStatus {
	if in == nil {
		return nil
	}
	out := new(SLOsStatus)
	in.DeepCopyInto(out)
	return out
}
