apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: StackServiceAccountToken
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/stackserviceaccounttoken
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: key_foo
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: cloud_sa

---

apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: StackServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/stackserviceaccounttoken
  labels:
    testing.upbound.io/example-name: cloud_sa
  name: cloud-sa
spec:
  forProvider:
    cloudStackSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isDisabled: false
    name: cloud service account
    role: Admin
