/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ProbeSetParameters defines the input parameters for the grafana_synthetic_monitoring_probes data source.
type ProbeSetParameters struct {
	// If true, only probes that are not deprecated will be returned. Defaults to `true`.
	// +optional
	FilterDeprecated *bool `json:"filterDeprecated,omitempty"`
}

// ProbeSetObservation holds the observed (computed) fields from the grafana_synthetic_monitoring_probes data source.
type ProbeSetObservation struct {
	// If true, only probes that are not deprecated will be returned. Defaults to `true`.
	FilterDeprecated *bool `json:"filterDeprecated,omitempty"`

	// Map of probes with their names as keys and IDs as values.
	Probes map[string]string `json:"probes,omitempty"`
}

type ProbeSetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProbeSetParameters `json:"forProvider"`
}

type ProbeSetStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ProbeSetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// ProbeSet is an observe-only resource backed by the grafana_synthetic_monitoring_probes Terraform data source.
type ProbeSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ProbeSetSpec   `json:"spec"`
	Status ProbeSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProbeSetList contains a list of ProbeSet.
type ProbeSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProbeSet `json:"items"`
}

var ProbeSet_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "ProbeSet",
}

func init() {
	SchemeBuilder.Register(&ProbeSet{}, &ProbeSetList{})
}
