apiVersion: enterprise.grafana.m.crossplane.io/v1alpha1
kind: DataSourcePermissionItem
metadata:
  annotations:
    meta.upbound.io/example-id: enterprise/v1alpha1/datasourcepermissionitem
  labels:
    testing.upbound.io/example-name: team
  name: team
  namespace: upbound-system
spec:
  forProvider:
    datasourceUid: ${grafana_data_source.foo.uid}
    permission: Edit
    team: ${grafana_team.team.id}

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: DataSource
metadata:
  annotations:
    meta.upbound.io/example-id: enterprise/v1alpha1/datasourcepermissionitem
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    jsonDataEncoded: |-
      ${jsonencode({
          defaultRegion = "us-east-1"
          authType      = "keys"
        })}
    name: cw-example
    secureJsonDataEncodedSecretRef:
      key: example-key
      name: example-secret
    type: cloudwatch

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: enterprise/v1alpha1/datasourcepermissionitem
  labels:
    testing.upbound.io/example-name: sa
  name: sa
  namespace: upbound-system
spec:
  forProvider:
    name: test-ds-permissions
    role: Viewer

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: enterprise/v1alpha1/datasourcepermissionitem
  labels:
    testing.upbound.io/example-name: team
  name: team
  namespace: upbound-system
spec:
  forProvider:
    name: Team Name

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: enterprise/v1alpha1/datasourcepermissionitem
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: upbound-system
spec:
  forProvider:
    email: test-ds-permissions@example.com
    login: test-ds-permissions
    name: test-ds-permissions
    passwordSecretRef:
      key: example-key
      name: example-secret
