apiVersion: oncall.grafana.o.crossplane.io/v1alpha1
kind: EscalationChain
metadata:
  name: example-escalationchain
  namespace: default
spec:
  forProvider:
    name: "example-name"
  providerConfigRef:
    name: example
