apiVersion: oncall.grafana.o.crossplane.io/v1alpha1
kind: Schedule
metadata:
  name: example-schedule
  namespace: default
spec:
  forProvider:
    name: "example-name"
  providerConfigRef:
    name: example
