apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: AlertruleV0Alpha1
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/alertrulev0alpha1
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metadata:
    - folderUid: ${grafana_folder.alertrule_folder.uid}
      uid: example-alert-rule
    spec:
    - annotations:
        runbook_url: https://example.com
      execErrState: KeepLast
      expressions:
        A: |-
          ${jsonencode({
                  model = {
                    datasource = {
                      type = "prometheus"
                      uid  = "ds_uid"
                    }
                    editorMode    = "code"
                    expr          = "count(up{})"
                    instant       = true
                    intervalMs    = 1000
                    legendFormat  = "__auto"
                    maxDataPoints = 43200
                    range         = false
                    refId         = "A"
                  }
                  datasource_uid = "ds_uid"
                  relative_time_range = {
                    from = "600s"
                    to   = "0s"
                  }
                  query_type = ""
                  source     = true
                })}
        B: |-
          ${jsonencode({
                  model = {
                    conditions = [
                      {
                        evaluator = {
                          params = [1]
                          type   = "gt"
                        }
                        operator = {
                          type = "and"
                        }
                        query = {
                          params = ["C"]
                        }
                        reducer = {
                          params = []
                          type   = "last"
                        }
                        type = "query"
                      }
                    ]
                    datasource = {
                      type = "__expr__"
                      uid  = "__expr__"
                    }
                    expression    = "A"
                    intervalMs    = 1000
                    maxDataPoints = 43200
                    refId         = "C"
                    type          = "threshold"
                  }
                  datasource_uid = "__expr__"
                  query_type     = ""
                  source         = false
                })}
      for: 5m
      labels:
        severity: critical
      missingSeriesEvalsToResolve: 5
      noDataState: KeepLast
      notificationSettings:
      - contactPoint: grafana-default-email
      panelRef:
        dashboard_uid: dashboard123
        panel_id: "5"
      paused: true
      title: Example Alert Rule
      trigger:
      - interval: 1m

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/alertrulev0alpha1
  labels:
    testing.upbound.io/example-name: alertrule_folder
  name: alertrule-folder
spec:
  forProvider:
    title: Alert Rule Folder
