apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: RulesequenceV0Alpha1
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/rulesequencev0alpha1
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metadata:
      folderUid: ${grafana_folder.rulesequence_folder.uid}
      uid: example-rule-sequence
    spec:
      alertingRules:
      - name: example-alert-rule
      recordingRules:
      - name: example-recording-rule
      trigger:
        interval: 1m

---

apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: AlertruleV0Alpha1
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/rulesequencev0alpha1
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metadata:
      folderUid: ${grafana_folder.rulesequence_folder.uid}
      uid: example-seq-alert-rule
    spec:
      execErrState: KeepLast
      expressions:
        A: |-
          ${jsonencode({
                  model = {
                    datasource = {
                      type = "prometheus"
                      uid  = "ds_uid"
                    }
                    editorMode    = "code"
                    expr          = "count(up{})"
                    instant       = true
                    intervalMs    = 1000
                    legendFormat  = "__auto"
                    maxDataPoints = 43200
                    range         = false
                    refId         = "A"
                  }
                  datasource_uid = "ds_uid"
                  relative_time_range = {
                    from = "600s"
                    to   = "0s"
                  }
                  query_type = ""
                  source     = true
                })}
      noDataState: KeepLast
      title: Example Sequence Alert Rule
      trigger:
        interval: 1m

---

apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: RecordingruleV0Alpha1
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/rulesequencev0alpha1
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metadata:
      folderUid: ${grafana_folder.rulesequence_folder.uid}
      uid: example-seq-recording-rule
    spec:
      expressions:
        A: |-
          ${jsonencode({
                  model = {
                    editorMode    = "code"
                    expr          = "count(up{})"
                    instant       = true
                    intervalMs    = 1000
                    legendFormat  = "__auto"
                    maxDataPoints = 43200
                    range         = false
                    refId         = "A"
                  }
                  datasource_uid = "ds_uid"
                  relative_time_range = {
                    from = "600s"
                    to   = "0s"
                  }
                  query_type = ""
                  source     = true
                })}
      metric: tf-seq-metric
      targetDatasourceUid: target_ds_uid
      title: Example Sequence Recording Rule
      trigger:
        interval: 1m

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: alerting/v1alpha1/rulesequencev0alpha1
  labels:
    testing.upbound.io/example-name: rulesequence_folder
  name: rulesequence-folder
spec:
  forProvider:
    title: Rule Sequence Folder
