apiVersion: assistant.grafana.crossplane.io/v1alpha1
kind: McpServer
metadata:
  annotations:
    meta.upbound.io/example-id: assistant/v1alpha1/mcpserver
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applications:
    - assistant
    configuration:
      url: https://example.com/mcp/
    customHeadersSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: Example MCP server
    scope: tenant
