/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccessPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccessPolicyToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrgMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PluginInstallation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivateDataSourceConnectNetwork) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivateDataSourceConnectNetworkToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Stack) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StackServiceAccount) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *StackServiceAccountToken) Hub() {}
