/*
Copyright 2025 Grafana
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ProjectLimitsParameters defines the input parameters for the grafana_k6_project_limits data source.
type ProjectLimitsParameters struct {
	// The identifier of the project to get limits for.
	// +kubebuilder:validation:Required
	ProjectID string `json:"projectID"`
}

// ProjectLimitsObservation holds the observed (computed) fields from the grafana_k6_project_limits data source.
type ProjectLimitsObservation struct {
	// Maximum duration of a test in seconds.
	DurationMaxPerTest *string `json:"durationMaxPerTest,omitempty"`

	// Maximum number of concurrent browser virtual users (VUs) used in one test.
	VuBrowserMaxPerTest *string `json:"vuBrowserMaxPerTest,omitempty"`

	// Maximum number of concurrent virtual users (VUs) used in one test.
	VuMaxPerTest *string `json:"vuMaxPerTest,omitempty"`

	// Maximum amount of virtual user hours (VU/h) used per one calendar month.
	VuhMaxPerMonth *string `json:"vuhMaxPerMonth,omitempty"`
}

type ProjectLimitsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectLimitsParameters `json:"forProvider"`
}

type ProjectLimitsStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ProjectLimitsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// ProjectLimits is an observe-only resource backed by the grafana_k6_project_limits Terraform data source.
type ProjectLimits struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ProjectLimitsSpec   `json:"spec"`
	Status ProjectLimitsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectLimitsList contains a list of ProjectLimits.
type ProjectLimitsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectLimits `json:"items"`
}

var ProjectLimits_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "ProjectLimits",
}

func init() {
	SchemeBuilder.Register(&ProjectLimits{}, &ProjectLimitsList{})
}
