/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// ProjectParameters defines the input parameters for the grafana_k6_project data source.
type ProjectParameters struct {
}

// ProjectObservation holds the observed (computed) fields from the grafana_k6_project data source.
type ProjectObservation struct {
	// The date when the project was created.
	Created *string `json:"created,omitempty"`

	// The Grafana folder uid.
	GrafanaFolderUID *string `json:"grafanaFolderUID,omitempty"`

	// Whether this project is the default for running tests when no explicit project identifier is provided.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Human-friendly identifier of the project.
	Name *string `json:"name,omitempty"`

	// The date when the project was last updated.
	Updated *string `json:"updated,omitempty"`
}

type ProjectSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectParameters `json:"forProvider"`
}

type ProjectStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Project is an observe-only resource backed by the grafana_k6_project Terraform data source.
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Project.
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

var Project_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "Project",
}

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
