apiVersion: cloudprovider.grafana.crossplane.io/v1alpha1
kind: AzureCredential
metadata:
  annotations:
    meta.upbound.io/example-id: cloudprovider/v1alpha1/azurecredential
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    autoDiscoveryConfiguration:
    - resourceTypeConfigurations:
      - metricConfiguration:
        - name: TotalCoresQuotaUsed
        resourceTypeName: Microsoft.App/containerApps
      - metricConfiguration:
        - aggregations:
          - Average
          dimensions:
          - GeoType
          - ApiName
          name: Availability
        resourceTypeName: Microsoft.Storage/storageAccounts/tableServices
      subscriptionId: my-subscription_id
    clientId: my-client-id
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    name: test-name
    resource_tags_to_add_to_metrics:
    - tag1
    - tag2
    resourceDiscoveryTagFilter:
    - key: key-1
      value: value-1
    - key: key-2
      value: value-2
    stackId: "1"
    tenantId: my-tenant-id
