/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// AwsCloudwatchScrapeJobSetParameters defines the input parameters for the grafana_cloud_provider_aws_cloudwatch_scrape_jobs data source.
type AwsCloudwatchScrapeJobSetParameters struct {
	// The Stack ID of the Grafana Cloud instance. Part of the Terraform Resource ID.
	// +kubebuilder:validation:Required
	StackID string `json:"stackID"`
}

// AwsCloudwatchScrapeJobSetObservation holds the observed (computed) fields from the grafana_cloud_provider_aws_cloudwatch_scrape_jobs data source.
type AwsCloudwatchScrapeJobSetObservation struct {
}

type AwsCloudwatchScrapeJobSetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AwsCloudwatchScrapeJobSetParameters `json:"forProvider"`
}

type AwsCloudwatchScrapeJobSetStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          AwsCloudwatchScrapeJobSetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// AwsCloudwatchScrapeJobSet is an observe-only resource backed by the grafana_cloud_provider_aws_cloudwatch_scrape_jobs Terraform data source.
type AwsCloudwatchScrapeJobSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AwsCloudwatchScrapeJobSetSpec   `json:"spec"`
	Status AwsCloudwatchScrapeJobSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AwsCloudwatchScrapeJobSetList contains a list of AwsCloudwatchScrapeJobSet.
type AwsCloudwatchScrapeJobSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AwsCloudwatchScrapeJobSet `json:"items"`
}

var AwsCloudwatchScrapeJobSet_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "AwsCloudwatchScrapeJobSet",
}

func init() {
	SchemeBuilder.Register(&AwsCloudwatchScrapeJobSet{}, &AwsCloudwatchScrapeJobSetList{})
}
