/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// SlackChannelParameters defines the input parameters for the grafana_oncall_slack_channel data source.
type SlackChannelParameters struct {
	// The Slack channel name.
	// +kubebuilder:validation:Required
	Name string `json:"name"`
}

// SlackChannelObservation holds the observed (computed) fields from the grafana_oncall_slack_channel data source.
type SlackChannelObservation struct {
	// The Slack ID of the channel.
	SlackID *string `json:"slackID,omitempty"`
}

type SlackChannelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SlackChannelParameters `json:"forProvider"`
}

type SlackChannelStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          SlackChannelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// SlackChannel is an observe-only resource backed by the grafana_oncall_slack_channel Terraform data source.
type SlackChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SlackChannelSpec   `json:"spec"`
	Status SlackChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SlackChannelList contains a list of SlackChannel.
type SlackChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SlackChannel `json:"items"`
}

var SlackChannel_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "SlackChannel",
}

func init() {
	SchemeBuilder.Register(&SlackChannel{}, &SlackChannelList{})
}
