/*
Copyright 2025 Grafana
*/

// Code generated by generate-observed; DO NOT EDIT.

package k6

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	v1alpha1 "github.com/grafana/crossplane-provider-grafana/v2/apis/observed/k6/v1alpha1"
	tfdatasource "github.com/grafana/crossplane-provider-grafana/v2/internal/controller/namespaced/observed/tfdatasource"
)

var ProjectAllowedLoadZonesSpec = tfdatasource.Spec{
	DataSourceName: "grafana_k6_project_allowed_load_zones",
	ManagedKind:    v1alpha1.ProjectAllowedLoadZones_GroupVersionKind,
	NewManaged:     func() resource.Managed { return &v1alpha1.ProjectAllowedLoadZones{} },
	Read: tfdatasource.NewFrameworkReadFn(
		newDSProjectAllowedLoadZones,
		func(mg resource.Managed) map[string]tftypes.Value {
			cr := mg.(*v1alpha1.ProjectAllowedLoadZones)
			attrs := map[string]tftypes.Value{}
			attrs["project_id"] = tftypes.NewValue(tftypes.String, cr.Spec.ForProvider.ProjectID)
			return attrs
		},
		func(ctx context.Context, mg resource.Managed, state tfsdk.State) {
			cr := mg.(*v1alpha1.ProjectAllowedLoadZones)
			{
				var v *string
				if diags := state.GetAttribute(ctx, path.Root("allowed_load_zones"), &v); !diags.HasError() && v != nil {
					cr.Status.AtProvider.AllowedLoadZones = v
				}
			}
		},
	),
}
