apiVersion: cloudintegrations.grafana.crossplane.io/v1alpha1
kind: CloudIntegration
metadata:
  annotations:
    meta.upbound.io/example-id: cloudintegrations/v1alpha1/cloudintegration
  labels:
    testing.upbound.io/example-name: linux-node
  name: linux-node
spec:
  forProvider:
    slug: linux-node
