/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package cloud

import (
	"context"

	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	v1alpha1 "github.com/grafana/crossplane-provider-grafana/v2/apis/observed/cloud/v1alpha1"
	tfdatasource "github.com/grafana/crossplane-provider-grafana/v2/pkg/tfdatasource"
)

var PrivateDataSourceConnectNetworksSpec = tfdatasource.Spec{
	DataSourceName: "grafana_cloud_private_data_source_connect_networks",
	ManagedKind:    v1alpha1.PrivateDataSourceConnectNetworks_GroupVersionKind,
	NewManaged:     func() resource.Managed { return &v1alpha1.PrivateDataSourceConnectNetworks{} },
	Read: tfdatasource.NewFrameworkReadFn(
		newDSPrivateDataSourceConnectNetworks,
		func(mg resource.Managed) map[string]tftypes.Value {
			cr := mg.(*v1alpha1.PrivateDataSourceConnectNetworks)
			attrs := map[string]tftypes.Value{}
			if cr.Spec.ForProvider.NameFilter != nil {
				attrs["name_filter"] = tftypes.NewValue(tftypes.String, *cr.Spec.ForProvider.NameFilter)
			}
			if cr.Spec.ForProvider.RegionFilter != nil {
				attrs["region_filter"] = tftypes.NewValue(tftypes.String, *cr.Spec.ForProvider.RegionFilter)
			}
			return attrs
		},
		func(ctx context.Context, mg resource.Managed, state tfsdk.State) {
			cr := mg.(*v1alpha1.PrivateDataSourceConnectNetworks)
			{
				var v *string
				if diags := state.GetAttribute(ctx, path.Root("name_filter"), &v); !diags.HasError() && v != nil {
					cr.Status.AtProvider.NameFilter = v
				}
			}
			{
				var v []string
				if diags := state.GetAttribute(ctx, path.Root("private_data_source_connect_networks"), &v); !diags.HasError() && len(v) > 0 {
					cr.Status.AtProvider.PrivateDataSourceConnectNetworks = v
				}
			}
			{
				var v *string
				if diags := state.GetAttribute(ctx, path.Root("region_filter"), &v); !diags.HasError() && v != nil {
					cr.Status.AtProvider.RegionFilter = v
				}
			}
		},
	),
	ConnectionDetailsFn: func(mg resource.Managed) managed.ConnectionDetails {
		cr := mg.(*v1alpha1.PrivateDataSourceConnectNetworks)
		cd := managed.ConnectionDetails{}
		if id := meta.GetExternalName(cr); id != "" {
			cd["id"] = []byte(id)
		}
		if cr.Status.AtProvider.NameFilter != nil {
			cd["name_filter"] = []byte(*cr.Status.AtProvider.NameFilter)
		}
		if cr.Status.AtProvider.RegionFilter != nil {
			cd["region_filter"] = []byte(*cr.Status.AtProvider.RegionFilter)
		}
		return cd
	},
}
