/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package cloud

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	sdkschema "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	v1alpha1 "github.com/grafana/crossplane-provider-grafana/v2/apis/observed/cloud/v1alpha1"
	tfdatasource "github.com/grafana/crossplane-provider-grafana/v2/pkg/tfdatasource"
)

var StackSpec = tfdatasource.Spec{
	DataSourceName: "grafana_cloud_stack",
	ManagedKind:    v1alpha1.Stack_GroupVersionKind,
	NewManaged:     func() resource.Managed { return &v1alpha1.Stack{} },
	Read: tfdatasource.NewLegacyReadFn(
		"grafana_cloud_stack",
		legacyDSStack,
		func(mg resource.Managed) map[string]string {
			cr := mg.(*v1alpha1.Stack)
			attrs := map[string]string{}
			attrs["slug"] = cr.Spec.ForProvider.Slug
			return attrs
		},
		func(mg resource.Managed, d *sdkschema.ResourceData) {
			cr := mg.(*v1alpha1.Stack)
			meta.SetExternalName(cr, d.Id())
			if v, ok := d.GetOk("alertmanager_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.AlertmanagerIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("alertmanager_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.AlertmanagerName = &s
				}
			}
			if v, ok := d.GetOk("alertmanager_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.AlertmanagerStatus = &s
				}
			}
			if v, ok := d.GetOk("alertmanager_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.AlertmanagerURL = &s
				}
			}
			if v, ok := d.GetOk("alertmanager_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.AlertmanagerUserID = &v
				}
			}
			if v, ok := d.GetOk("cluster_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ClusterName = &s
				}
			}
			if v, ok := d.GetOk("cluster_slug"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ClusterSlug = &s
				}
			}
			if v, ok := d.GetOk("delete_protection"); ok {
				if b, ok := v.(bool); ok {
					cr.Status.AtProvider.DeleteProtection = &b
				}
			}
			if v, ok := d.GetOk("description"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Description = &s
				}
			}
			if v, ok := d.GetOk("fleet_management_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FleetManagementName = &s
				}
			}
			// TODO: complex type []string for fleet_management_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("fleet_management_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FleetManagementPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for fleet_management_private_connectivity_info_regions
			if v, ok := d.GetOk("fleet_management_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FleetManagementPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("fleet_management_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FleetManagementStatus = &s
				}
			}
			if v, ok := d.GetOk("fleet_management_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FleetManagementURL = &s
				}
			}
			if v, ok := d.GetOk("fleet_management_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.FleetManagementUserID = &v
				}
			}
			if v, ok := d.GetOk("grafanas_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GrafanasIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("graphite_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphiteIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("graphite_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphiteName = &s
				}
			}
			// TODO: complex type []string for graphite_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("graphite_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphitePrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for graphite_private_connectivity_info_regions
			if v, ok := d.GetOk("graphite_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphitePrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("graphite_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphiteStatus = &s
				}
			}
			if v, ok := d.GetOk("graphite_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.GraphiteURL = &s
				}
			}
			if v, ok := d.GetOk("graphite_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.GraphiteUserID = &v
				}
			}
			if v, ok := d.GetOk("influx_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.InfluxURL = &s
				}
			}
			// TODO: complex type map[string]string for labels
			if v, ok := d.GetOk("logs_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("logs_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsName = &s
				}
			}
			// TODO: complex type []string for logs_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("logs_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for logs_private_connectivity_info_regions
			if v, ok := d.GetOk("logs_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("logs_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsStatus = &s
				}
			}
			if v, ok := d.GetOk("logs_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.LogsURL = &s
				}
			}
			if v, ok := d.GetOk("logs_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.LogsUserID = &v
				}
			}
			if v, ok := d.GetOk("name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Name = &s
				}
			}
			if v, ok := d.GetOk("oncall_api_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OncallAPIURL = &s
				}
			}
			if v, ok := d.GetOk("org_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.OrgID = &v
				}
			}
			if v, ok := d.GetOk("org_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OrgName = &s
				}
			}
			if v, ok := d.GetOk("org_slug"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OrgSlug = &s
				}
			}
			// TODO: complex type []string for otlp_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("otlp_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OtlpPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for otlp_private_connectivity_info_regions
			if v, ok := d.GetOk("otlp_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OtlpPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("otlp_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OtlpURL = &s
				}
			}
			// TODO: complex type []string for pdc_api_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("pdc_api_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PdcAPIPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for pdc_api_private_connectivity_info_regions
			if v, ok := d.GetOk("pdc_api_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PdcAPIPrivateConnectivityInfoServiceName = &s
				}
			}
			// TODO: complex type []string for pdc_gateway_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("pdc_gateway_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PdcGatewayPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for pdc_gateway_private_connectivity_info_regions
			if v, ok := d.GetOk("pdc_gateway_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PdcGatewayPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("profiles_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("profiles_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesName = &s
				}
			}
			// TODO: complex type []string for profiles_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("profiles_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for profiles_private_connectivity_info_regions
			if v, ok := d.GetOk("profiles_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("profiles_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesStatus = &s
				}
			}
			if v, ok := d.GetOk("profiles_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ProfilesURL = &s
				}
			}
			if v, ok := d.GetOk("profiles_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.ProfilesUserID = &v
				}
			}
			if v, ok := d.GetOk("prometheus_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("prometheus_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusName = &s
				}
			}
			// TODO: complex type []string for prometheus_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("prometheus_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for prometheus_private_connectivity_info_regions
			if v, ok := d.GetOk("prometheus_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("prometheus_remote_endpoint"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusRemoteEndpoint = &s
				}
			}
			if v, ok := d.GetOk("prometheus_remote_write_endpoint"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusRemoteWriteEndpoint = &s
				}
			}
			if v, ok := d.GetOk("prometheus_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusStatus = &s
				}
			}
			if v, ok := d.GetOk("prometheus_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.PrometheusURL = &s
				}
			}
			if v, ok := d.GetOk("prometheus_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.PrometheusUserID = &v
				}
			}
			if v, ok := d.GetOk("region_slug"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.RegionSlug = &s
				}
			}
			if v, ok := d.GetOk("status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Status = &s
				}
			}
			if v, ok := d.GetOk("traces_ip_allow_list_cname"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesIPAllowListCname = &s
				}
			}
			if v, ok := d.GetOk("traces_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesName = &s
				}
			}
			// TODO: complex type []string for traces_private_connectivity_info_availability_zones
			if v, ok := d.GetOk("traces_private_connectivity_info_private_dns"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesPrivateConnectivityInfoPrivateDNS = &s
				}
			}
			// TODO: complex type []string for traces_private_connectivity_info_regions
			if v, ok := d.GetOk("traces_private_connectivity_info_service_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesPrivateConnectivityInfoServiceName = &s
				}
			}
			if v, ok := d.GetOk("traces_status"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesStatus = &s
				}
			}
			if v, ok := d.GetOk("traces_url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.TracesURL = &s
				}
			}
			if v, ok := d.GetOk("traces_user_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.TracesUserID = &v
				}
			}
			if v, ok := d.GetOk("url"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.URL = &s
				}
			}
		},
	),
}
