apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: APIKey
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/apikey
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    name: key_foo
    role: Viewer
