apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folder
  labels:
    testing.upbound.io/example-name: test_folder
  name: test-folder
spec:
  forProvider:
    title: Terraform Test Folder

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/folder
  labels:
    testing.upbound.io/example-name: test_folder
  name: test-folder
spec:
  forProvider:
    configJson: |
      {
        "title": "Dashboard in folder",
        "uid": "dashboard-in-folder"
      }
    folderSelector:
      matchLabels:
        testing.upbound.io/example-name: test_folder
