apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/organization
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    adminUser: admin
    admins:
    - admin@example.com
    createUsers: true
    editors:
    - editor-01@example.com
    - editor-02@example.com
    name: Test Organization
    viewers:
    - viewer-01@example.com
    - viewer-02@example.com
