apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccountPermission
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermission
  labels:
    testing.upbound.io/example-name: test_permissions
  name: test-permissions
spec:
  forProvider:
    permissions:
    - permission: Edit
      userSelector:
        matchLabels:
          testing.upbound.io/example-name: test_user
    - permission: Admin
      teamSelector:
        matchLabels:
          testing.upbound.io/example-name: test_team
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermission
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    isDisabled: false
    name: sa-terraform-test
    role: Editor

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermission
  labels:
    testing.upbound.io/example-name: test_team
  name: test-team
spec:
  forProvider:
    name: tf_test_team

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccountpermission
  labels:
    testing.upbound.io/example-name: test_user
  name: test-user
spec:
  forProvider:
    email: tf_user@test.com
    login: tf_user@test.com
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
