# Note: Resources are inverted in this file so that the dashboard is deleted first,
# it will fail to delete if the SA token is deleted first.
# Creation order doesn't matter because Crossplane is eventually consistent

# Create a new dashboard using the new provider
apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Dashboard
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccounttoken
  labels:
    testing.upbound.io/example-name: test-sa-token
  name: test-dashboard-from-sa
spec:
  forProvider:
    configJson: |-
      {
        "title" : "My Dashboard From SA Token",
        "uid" : "dashboard-from-sa"
      }
  providerConfigRef:
    name: sa-grafana-provider

---

# Create a new provider from the created secret
apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccounttoken
  labels:
    testing.upbound.io/example-name: test-sa-token
  name: sa-grafana-provider
spec:
  url: http://grafana.grafana.svc.cluster.local # Same as the grafana-provider URL
  credentials:
    source: Secret
    secretRef:
      name: test-sa-token
      namespace: upbound-system
      key: instanceCredentials

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccountToken
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccounttoken
    uptest.upbound.io/disable-import: "true"
  labels:
    testing.upbound.io/example-name: test-sa-token
  name: test-sa-token
spec:
  forProvider:
    name: test-sa-token
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: test-sa-token
  writeConnectionSecretToRef:
    name: test-sa-token
    namespace: upbound-system
  providerConfigRef:
    name: grafana-provider

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/serviceaccounttoken
  labels:
    testing.upbound.io/example-name: test-sa-token
  name: test-sa
spec:
  forProvider:
    name: test-sa
    role: Admin
  providerConfigRef:
    name: grafana-provider
