apiVersion: k6.grafana.crossplane.io/v1alpha1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: k6/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: daily
  name: daily
spec:
  forProvider:
    loadTestId: ${grafana_k6_load_test.scheduled_test.id}
    recurrenceRule:
    - frequency: DAILY
      interval: 1
    starts: "2024-12-25T10:00:00Z"

---

apiVersion: k6.grafana.crossplane.io/v1alpha1
kind: LoadTest
metadata:
  annotations:
    meta.upbound.io/example-id: k6/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: scheduled_test
  name: scheduled-test
spec:
  forProvider:
    name: Terraform Scheduled Resource Test
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: schedule_project
    script: |
      export default function() {
        console.log('Hello from scheduled k6 test!');
      }

---

apiVersion: k6.grafana.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: k6/v1alpha1/schedule
  labels:
    testing.upbound.io/example-name: schedule_project
  name: schedule-project
spec:
  forProvider:
    name: Terraform Schedule Resource Project
