apiVersion: cloud.grafana.o.crossplane.io/v1alpha1
kind: PrivateDataSourceConnectNetworks
metadata:
  name: example-privatedatasourceconnectnetworks
  namespace: default
spec:
  forProvider:
    nameFilter: "example-name_filter"
    regionFilter: "example-region_filter"
  providerConfigRef:
    name: example
