/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package oss

import (
	"fmt"
	"strconv"

	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	sdkschema "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	v1alpha1 "github.com/grafana/crossplane-provider-grafana/v2/apis/observed/oss/v1alpha1"
	tfdatasource "github.com/grafana/crossplane-provider-grafana/v2/pkg/tfdatasource"
)

var LibraryPanelSpec = tfdatasource.Spec{
	DataSourceName: "grafana_library_panel",
	ManagedKind:    v1alpha1.LibraryPanel_GroupVersionKind,
	NewManaged:     func() resource.Managed { return &v1alpha1.LibraryPanel{} },
	Read: tfdatasource.NewLegacyReadFn(
		"grafana_library_panel",
		legacyDSLibraryPanel,
		func(mg resource.Managed) map[string]string {
			cr := mg.(*v1alpha1.LibraryPanel)
			attrs := map[string]string{}
			if cr.Spec.ForProvider.Name != nil {
				attrs["name"] = fmt.Sprintf("%v", *cr.Spec.ForProvider.Name)
			}
			if cr.Spec.ForProvider.OrgID != nil {
				attrs["org_id"] = fmt.Sprintf("%v", *cr.Spec.ForProvider.OrgID)
			}
			if cr.Spec.ForProvider.UID != nil {
				attrs["uid"] = fmt.Sprintf("%v", *cr.Spec.ForProvider.UID)
			}
			return attrs
		},
		func(mg resource.Managed, d *sdkschema.ResourceData) {
			cr := mg.(*v1alpha1.LibraryPanel)
			meta.SetExternalName(cr, d.Id())
			if v, ok := d.GetOk("created"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Created = &s
				}
			}
			// TODO: complex type []int64 for dashboard_ids
			if v, ok := d.GetOk("description"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Description = &s
				}
			}
			if v, ok := d.GetOk("folder_name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FolderName = &s
				}
			}
			if v, ok := d.GetOk("folder_uid"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.FolderUID = &s
				}
			}
			if v, ok := d.GetOk("model_json"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.ModelJSON = &s
				}
			}
			if v, ok := d.GetOk("name"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Name = &s
				}
			}
			if v, ok := d.GetOk("org_id"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.OrgID = &s
				}
			}
			if v, ok := d.GetOk("panel_id"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.PanelID = &v
				}
			}
			if v, ok := d.GetOk("type"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Type = &s
				}
			}
			if v, ok := d.GetOk("uid"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.UID = &s
				}
			}
			if v, ok := d.GetOk("updated"); ok {
				if s, ok := v.(string); ok {
					cr.Status.AtProvider.Updated = &s
				}
			}
			if v, ok := d.GetOk("version"); ok {
				if i, ok := v.(int); ok {
					v := int64(i)
					cr.Status.AtProvider.Version = &v
				}
			}
		},
	),
	ConnectionDetailsFn: func(mg resource.Managed) managed.ConnectionDetails {
		cr := mg.(*v1alpha1.LibraryPanel)
		cd := managed.ConnectionDetails{}
		if cr.Status.AtProvider.Created != nil {
			cd["created"] = []byte(*cr.Status.AtProvider.Created)
		}
		if cr.Status.AtProvider.Description != nil {
			cd["description"] = []byte(*cr.Status.AtProvider.Description)
		}
		if cr.Status.AtProvider.FolderName != nil {
			cd["folder_name"] = []byte(*cr.Status.AtProvider.FolderName)
		}
		if cr.Status.AtProvider.FolderUID != nil {
			cd["folder_uid"] = []byte(*cr.Status.AtProvider.FolderUID)
		}
		if cr.Status.AtProvider.ModelJSON != nil {
			cd["model_json"] = []byte(*cr.Status.AtProvider.ModelJSON)
		}
		if cr.Status.AtProvider.Name != nil {
			cd["name"] = []byte(*cr.Status.AtProvider.Name)
		}
		if cr.Status.AtProvider.OrgID != nil {
			cd["org_id"] = []byte(*cr.Status.AtProvider.OrgID)
		}
		if cr.Status.AtProvider.PanelID != nil {
			cd["panel_id"] = []byte(strconv.FormatInt(*cr.Status.AtProvider.PanelID, 10))
		}
		if cr.Status.AtProvider.Type != nil {
			cd["type"] = []byte(*cr.Status.AtProvider.Type)
		}
		if cr.Status.AtProvider.UID != nil {
			cd["uid"] = []byte(*cr.Status.AtProvider.UID)
		}
		if cr.Status.AtProvider.Updated != nil {
			cd["updated"] = []byte(*cr.Status.AtProvider.Updated)
		}
		if cr.Status.AtProvider.Version != nil {
			cd["version"] = []byte(strconv.FormatInt(*cr.Status.AtProvider.Version, 10))
		}
		return cd
	},
}
