apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: grafana-cloud-instance-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: my-stack-secret
      namespace: crossplane
      key: instanceCredentials

