apiVersion: cloudprovider.grafana.o.crossplane.io/v1alpha1
kind: AwsCloudwatchScrapeJobSet
metadata:
  name: example-awscloudwatchscrapejobset
  namespace: default
spec:
  forProvider:
    stackID: "example-stack_id"
  providerConfigRef:
    name: example
