apiVersion: cloudprovider.grafana.o.crossplane.io/v1alpha1
kind: AzureCredential
metadata:
  name: example-azurecredential
  namespace: default
spec:
  forProvider:
    resourceID: "example-resource_id"
    stackID: "example-stack_id"
  providerConfigRef:
    name: example
