/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PreferencesObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PreferencesParameters struct {

	// The Organization home dashboard ID.
	// +kubebuilder:validation:Optional
	HomeDashboardID *float64 `json:"homeDashboardId,omitempty" tf:"home_dashboard_id,omitempty"`

	// The Organization home dashboard UID. This is only available in Grafana 9.0+.
	// +kubebuilder:validation:Optional
	HomeDashboardUID *string `json:"homeDashboardUid,omitempty" tf:"home_dashboard_uid,omitempty"`

	// The Organization ID. If not set, the Org ID defined in the provider block will be used.
	// +crossplane:generate:reference:type=github.com/grafana/crossplane-provider-grafana/apis/oss/v1alpha1.Organization
	// +crossplane:generate:reference:refFieldName=OrganizationRef
	// +crossplane:generate:reference:selectorFieldName=OrganizationSelector
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in oss to populate orgId.
	// +kubebuilder:validation:Optional
	OrganizationRef *v1.Reference `json:"organizationRef,omitempty" tf:"-"`

	// Selector for a Organization in oss to populate orgId.
	// +kubebuilder:validation:Optional
	OrganizationSelector *v1.Selector `json:"organizationSelector,omitempty" tf:"-"`

	// The Organization theme. Available values are `light`, `dark`, or an empty string for the default.
	// +kubebuilder:validation:Optional
	Theme *string `json:"theme,omitempty" tf:"theme,omitempty"`

	// The Organization timezone. Available values are `utc`, `browser`, or an empty string for the default.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The Organization week start.
	// +kubebuilder:validation:Optional
	WeekStart *string `json:"weekStart,omitempty" tf:"week_start,omitempty"`
}

// PreferencesSpec defines the desired state of Preferences
type PreferencesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PreferencesParameters `json:"forProvider"`
}

// PreferencesStatus defines the observed state of Preferences.
type PreferencesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PreferencesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Preferences is the Schema for the Preferencess API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,grafana}
type Preferences struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PreferencesSpec   `json:"spec"`
	Status            PreferencesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PreferencesList contains a list of Preferencess
type PreferencesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Preferences `json:"items"`
}

// Repository type metadata.
var (
	Preferences_Kind             = "Preferences"
	Preferences_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Preferences_Kind}.String()
	Preferences_KindAPIVersion   = Preferences_Kind + "." + CRDGroupVersion.String()
	Preferences_GroupVersionKind = CRDGroupVersion.WithKind(Preferences_Kind)
)

func init() {
	SchemeBuilder.Register(&Preferences{}, &PreferencesList{})
}
