apiVersion: asserts.grafana.m.crossplane.io/v1alpha1
kind: PromRuleFile
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/promrulefile
  labels:
    testing.upbound.io/example-name: latency_metrics
  name: latency-metrics
  namespace: upbound-system
spec:
  forProvider:
    active: true
    group:
    - interval: 30s
      name: latency_recording_rules
      rule:
      - expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
        labels:
          severity: info
          source: custom_instrumentation
        record: custom:latency:p95
      - expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))
        labels:
          severity: info
          source: custom_instrumentation
        record: custom:latency:p99
    name: custom-latency-metrics
