apiVersion: asserts.grafana.m.crossplane.io/v1alpha1
kind: Stack
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/stack
  labels:
    testing.upbound.io/example-name: main
  name: main
  namespace: upbound-system
spec:
  forProvider:
    cloudAccessPolicyTokenSecretRef:
      key: attribute.token
      name: example-cloud-access-policy-token
    grafanaTokenSecretRef:
      key: attribute.key
      name: example-cloud-stack-service-account-token

---

apiVersion: cloud.grafana.m.crossplane.io/v1alpha1
kind: AccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/stack
  labels:
    testing.upbound.io/example-name: asserts
  name: asserts
  namespace: upbound-system
spec:
  forProvider:
    displayName: Asserts Stack Policy
    name: asserts-stack-policy
    realm:
    - stackSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      type: stack
    scopes:
    - stacks:read
    - metrics:read
    - metrics:write

---

apiVersion: cloud.grafana.m.crossplane.io/v1alpha1
kind: AccessPolicyToken
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/stack
  labels:
    testing.upbound.io/example-name: asserts
  name: asserts
  namespace: upbound-system
spec:
  forProvider:
    accessPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: asserts
    name: asserts-stack-token

---

apiVersion: cloud.grafana.m.crossplane.io/v1alpha1
kind: StackServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/stack
  labels:
    testing.upbound.io/example-name: asserts
  name: asserts
  namespace: upbound-system
spec:
  forProvider:
    cloudStackSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isDisabled: false
    name: asserts-managed-alerts-sa
    role: Admin

---

apiVersion: cloud.grafana.m.crossplane.io/v1alpha1
kind: StackServiceAccountToken
metadata:
  annotations:
    meta.upbound.io/example-id: asserts/v1alpha1/stack
  labels:
    testing.upbound.io/example-name: asserts
  name: asserts
  namespace: upbound-system
spec:
  forProvider:
    cloudStackSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: asserts-managed-alerts-token
    serviceAccountSelector:
      matchLabels:
        testing.upbound.io/example-name: asserts
