apiVersion: fleetmanagement.grafana.o.crossplane.io/v1alpha1
kind: Collector
metadata:
  name: example-collector
  namespace: default
spec:
  forProvider:
    {}
  providerConfigRef:
    name: example
