/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AllowedToolsInitParameters struct {

	// (String) Integration UUID.
	// Integration UUID.
	IntegrationID *string `json:"integrationId,omitempty" tf:"integration_id,omitempty"`

	// (String) MCP tool name.
	// MCP tool name.
	ToolName *string `json:"toolName,omitempty" tf:"tool_name,omitempty"`
}

type AllowedToolsObservation struct {

	// (String) Integration UUID.
	// Integration UUID.
	IntegrationID *string `json:"integrationId,omitempty" tf:"integration_id,omitempty"`

	// (String) MCP tool name.
	// MCP tool name.
	ToolName *string `json:"toolName,omitempty" tf:"tool_name,omitempty"`
}

type AllowedToolsParameters struct {

	// (String) Integration UUID.
	// Integration UUID.
	// +kubebuilder:validation:Optional
	IntegrationID *string `json:"integrationId" tf:"integration_id,omitempty"`

	// (String) MCP tool name.
	// MCP tool name.
	// +kubebuilder:validation:Optional
	ToolName *string `json:"toolName" tf:"tool_name,omitempty"`
}

type SkillInitParameters struct {

	// approve when this skill is invoked. (see below for nested schema)
	// MCP tools to auto-approve when this skill is invoked.
	AllowedTools []AllowedToolsInitParameters `json:"allowedTools,omitempty" tf:"allowed_tools,omitempty"`

	// (String) The skill content.
	// The skill content.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Optional JSON array of context items referenced by the skill.
	// Optional JSON array of context items referenced by the skill.
	ContextItems *string `json:"contextItems,omitempty" tf:"context_items,omitempty"`

	// (Boolean) Whether the skill is included in the knowledgebase.
	// Whether the skill is included in the knowledgebase.
	IncludeInKnowledgebase *bool `json:"includeInKnowledgebase,omitempty" tf:"include_in_knowledgebase,omitempty"`

	// (String) The skill name.
	// The skill name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Whether the resource is visible to the whole tenant (tenant) or only the creating user (user).
	// Whether the resource is visible to the whole tenant (`tenant`) or only the creating user (`user`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type SkillObservation struct {

	// approve when this skill is invoked. (see below for nested schema)
	// MCP tools to auto-approve when this skill is invoked.
	AllowedTools []AllowedToolsObservation `json:"allowedTools,omitempty" tf:"allowed_tools,omitempty"`

	// (String) The skill content.
	// The skill content.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Optional JSON array of context items referenced by the skill.
	// Optional JSON array of context items referenced by the skill.
	ContextItems *string `json:"contextItems,omitempty" tf:"context_items,omitempty"`

	// (String) The UUID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether the skill is included in the knowledgebase.
	// Whether the skill is included in the knowledgebase.
	IncludeInKnowledgebase *bool `json:"includeInKnowledgebase,omitempty" tf:"include_in_knowledgebase,omitempty"`

	// (String) The skill name.
	// The skill name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Whether the resource is visible to the whole tenant (tenant) or only the creating user (user).
	// Whether the resource is visible to the whole tenant (`tenant`) or only the creating user (`user`).
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type SkillParameters struct {

	// approve when this skill is invoked. (see below for nested schema)
	// MCP tools to auto-approve when this skill is invoked.
	// +kubebuilder:validation:Optional
	AllowedTools []AllowedToolsParameters `json:"allowedTools,omitempty" tf:"allowed_tools,omitempty"`

	// (String) The skill content.
	// The skill content.
	// +kubebuilder:validation:Optional
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// (String) Optional JSON array of context items referenced by the skill.
	// Optional JSON array of context items referenced by the skill.
	// +kubebuilder:validation:Optional
	ContextItems *string `json:"contextItems,omitempty" tf:"context_items,omitempty"`

	// (Boolean) Whether the skill is included in the knowledgebase.
	// Whether the skill is included in the knowledgebase.
	// +kubebuilder:validation:Optional
	IncludeInKnowledgebase *bool `json:"includeInKnowledgebase,omitempty" tf:"include_in_knowledgebase,omitempty"`

	// (String) The skill name.
	// The skill name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Whether the resource is visible to the whole tenant (tenant) or only the creating user (user).
	// Whether the resource is visible to the whole tenant (`tenant`) or only the creating user (`user`).
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

// SkillSpec defines the desired state of Skill
type SkillSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SkillParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SkillInitParameters `json:"initProvider,omitempty"`
}

// SkillStatus defines the observed state of Skill.
type SkillStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SkillObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Skill is the Schema for the Skills API. Manages a Grafana Assistant skill.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,grafana}
type Skill struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.body) || (has(self.initProvider) && has(self.initProvider.body))",message="spec.forProvider.body is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scope) || (has(self.initProvider) && has(self.initProvider.scope))",message="spec.forProvider.scope is a required parameter"
	Spec   SkillSpec   `json:"spec"`
	Status SkillStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SkillList contains a list of Skills
type SkillList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Skill `json:"items"`
}

// Repository type metadata.
var (
	Skill_Kind             = "Skill"
	Skill_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Skill_Kind}.String()
	Skill_KindAPIVersion   = Skill_Kind + "." + CRDGroupVersion.String()
	Skill_GroupVersionKind = CRDGroupVersion.WithKind(Skill_Kind)
)

func init() {
	SchemeBuilder.Register(&Skill{}, &SkillList{})
}
