//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicies) DeepCopyInto(out *AccessPolicies) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicies.
func (in *AccessPolicies) DeepCopy() *AccessPolicies {
	if in == nil {
		return nil
	}
	out := new(AccessPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessPolicies) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoliciesList) DeepCopyInto(out *AccessPoliciesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessPolicies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoliciesList.
func (in *AccessPoliciesList) DeepCopy() *AccessPoliciesList {
	if in == nil {
		return nil
	}
	out := new(AccessPoliciesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessPoliciesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoliciesObservation) DeepCopyInto(out *AccessPoliciesObservation) {
	*out = *in
	if in.AccessPolicies != nil {
		in, out := &in.AccessPolicies, &out.AccessPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NameFilter != nil {
		in, out := &in.NameFilter, &out.NameFilter
		*out = new(string)
		**out = **in
	}
	if in.RegionFilter != nil {
		in, out := &in.RegionFilter, &out.RegionFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoliciesObservation.
func (in *AccessPoliciesObservation) DeepCopy() *AccessPoliciesObservation {
	if in == nil {
		return nil
	}
	out := new(AccessPoliciesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoliciesParameters) DeepCopyInto(out *AccessPoliciesParameters) {
	*out = *in
	if in.NameFilter != nil {
		in, out := &in.NameFilter, &out.NameFilter
		*out = new(string)
		**out = **in
	}
	if in.RegionFilter != nil {
		in, out := &in.RegionFilter, &out.RegionFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoliciesParameters.
func (in *AccessPoliciesParameters) DeepCopy() *AccessPoliciesParameters {
	if in == nil {
		return nil
	}
	out := new(AccessPoliciesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoliciesSpec) DeepCopyInto(out *AccessPoliciesSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoliciesSpec.
func (in *AccessPoliciesSpec) DeepCopy() *AccessPoliciesSpec {
	if in == nil {
		return nil
	}
	out := new(AccessPoliciesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPoliciesStatus) DeepCopyInto(out *AccessPoliciesStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPoliciesStatus.
func (in *AccessPoliciesStatus) DeepCopy() *AccessPoliciesStatus {
	if in == nil {
		return nil
	}
	out := new(AccessPoliciesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPS) DeepCopyInto(out *IPS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPS.
func (in *IPS) DeepCopy() *IPS {
	if in == nil {
		return nil
	}
	out := new(IPS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSList) DeepCopyInto(out *IPSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSList.
func (in *IPSList) DeepCopy() *IPSList {
	if in == nil {
		return nil
	}
	out := new(IPSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSObservation) DeepCopyInto(out *IPSObservation) {
	*out = *in
	if in.HostedAlerts != nil {
		in, out := &in.HostedAlerts, &out.HostedAlerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedGrafana != nil {
		in, out := &in.HostedGrafana, &out.HostedGrafana
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedLogs != nil {
		in, out := &in.HostedLogs, &out.HostedLogs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedMetrics != nil {
		in, out := &in.HostedMetrics, &out.HostedMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedOtlp != nil {
		in, out := &in.HostedOtlp, &out.HostedOtlp
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedProfiles != nil {
		in, out := &in.HostedProfiles, &out.HostedProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostedTraces != nil {
		in, out := &in.HostedTraces, &out.HostedTraces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSObservation.
func (in *IPSObservation) DeepCopy() *IPSObservation {
	if in == nil {
		return nil
	}
	out := new(IPSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSParameters) DeepCopyInto(out *IPSParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSParameters.
func (in *IPSParameters) DeepCopy() *IPSParameters {
	if in == nil {
		return nil
	}
	out := new(IPSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSSpec) DeepCopyInto(out *IPSSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSSpec.
func (in *IPSSpec) DeepCopy() *IPSSpec {
	if in == nil {
		return nil
	}
	out := new(IPSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSStatus) DeepCopyInto(out *IPSStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSStatus.
func (in *IPSStatus) DeepCopy() *IPSStatus {
	if in == nil {
		return nil
	}
	out := new(IPSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationObservation) DeepCopyInto(out *OrganizationObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationObservation.
func (in *OrganizationObservation) DeepCopy() *OrganizationObservation {
	if in == nil {
		return nil
	}
	out := new(OrganizationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationParameters) DeepCopyInto(out *OrganizationParameters) {
	*out = *in
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationParameters.
func (in *OrganizationParameters) DeepCopy() *OrganizationParameters {
	if in == nil {
		return nil
	}
	out := new(OrganizationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworks) DeepCopyInto(out *PrivateDataSourceConnectNetworks) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworks.
func (in *PrivateDataSourceConnectNetworks) DeepCopy() *PrivateDataSourceConnectNetworks {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateDataSourceConnectNetworks) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworksList) DeepCopyInto(out *PrivateDataSourceConnectNetworksList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateDataSourceConnectNetworks, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworksList.
func (in *PrivateDataSourceConnectNetworksList) DeepCopy() *PrivateDataSourceConnectNetworksList {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworksList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateDataSourceConnectNetworksList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworksObservation) DeepCopyInto(out *PrivateDataSourceConnectNetworksObservation) {
	*out = *in
	if in.NameFilter != nil {
		in, out := &in.NameFilter, &out.NameFilter
		*out = new(string)
		**out = **in
	}
	if in.PrivateDataSourceConnectNetworks != nil {
		in, out := &in.PrivateDataSourceConnectNetworks, &out.PrivateDataSourceConnectNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegionFilter != nil {
		in, out := &in.RegionFilter, &out.RegionFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworksObservation.
func (in *PrivateDataSourceConnectNetworksObservation) DeepCopy() *PrivateDataSourceConnectNetworksObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworksObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworksParameters) DeepCopyInto(out *PrivateDataSourceConnectNetworksParameters) {
	*out = *in
	if in.NameFilter != nil {
		in, out := &in.NameFilter, &out.NameFilter
		*out = new(string)
		**out = **in
	}
	if in.RegionFilter != nil {
		in, out := &in.RegionFilter, &out.RegionFilter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworksParameters.
func (in *PrivateDataSourceConnectNetworksParameters) DeepCopy() *PrivateDataSourceConnectNetworksParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworksParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworksSpec) DeepCopyInto(out *PrivateDataSourceConnectNetworksSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworksSpec.
func (in *PrivateDataSourceConnectNetworksSpec) DeepCopy() *PrivateDataSourceConnectNetworksSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateDataSourceConnectNetworksStatus) DeepCopyInto(out *PrivateDataSourceConnectNetworksStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateDataSourceConnectNetworksStatus.
func (in *PrivateDataSourceConnectNetworksStatus) DeepCopy() *PrivateDataSourceConnectNetworksStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateDataSourceConnectNetworksStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Stack) DeepCopyInto(out *Stack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Stack.
func (in *Stack) DeepCopy() *Stack {
	if in == nil {
		return nil
	}
	out := new(Stack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Stack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackList) DeepCopyInto(out *StackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Stack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackList.
func (in *StackList) DeepCopy() *StackList {
	if in == nil {
		return nil
	}
	out := new(StackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackObservation) DeepCopyInto(out *StackObservation) {
	*out = *in
	if in.AlertmanagerIPAllowListCname != nil {
		in, out := &in.AlertmanagerIPAllowListCname, &out.AlertmanagerIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.AlertmanagerName != nil {
		in, out := &in.AlertmanagerName, &out.AlertmanagerName
		*out = new(string)
		**out = **in
	}
	if in.AlertmanagerStatus != nil {
		in, out := &in.AlertmanagerStatus, &out.AlertmanagerStatus
		*out = new(string)
		**out = **in
	}
	if in.AlertmanagerURL != nil {
		in, out := &in.AlertmanagerURL, &out.AlertmanagerURL
		*out = new(string)
		**out = **in
	}
	if in.AlertmanagerUserID != nil {
		in, out := &in.AlertmanagerUserID, &out.AlertmanagerUserID
		*out = new(int64)
		**out = **in
	}
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.ClusterSlug != nil {
		in, out := &in.ClusterSlug, &out.ClusterSlug
		*out = new(string)
		**out = **in
	}
	if in.DeleteProtection != nil {
		in, out := &in.DeleteProtection, &out.DeleteProtection
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementName != nil {
		in, out := &in.FleetManagementName, &out.FleetManagementName
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.FleetManagementPrivateConnectivityInfoAvailabilityZoneIDs, &out.FleetManagementPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FleetManagementPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.FleetManagementPrivateConnectivityInfoAvailabilityZones, &out.FleetManagementPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FleetManagementPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.FleetManagementPrivateConnectivityInfoPrivateDNS, &out.FleetManagementPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementPrivateConnectivityInfoRegions != nil {
		in, out := &in.FleetManagementPrivateConnectivityInfoRegions, &out.FleetManagementPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FleetManagementPrivateConnectivityInfoServiceName != nil {
		in, out := &in.FleetManagementPrivateConnectivityInfoServiceName, &out.FleetManagementPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementStatus != nil {
		in, out := &in.FleetManagementStatus, &out.FleetManagementStatus
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementURL != nil {
		in, out := &in.FleetManagementURL, &out.FleetManagementURL
		*out = new(string)
		**out = **in
	}
	if in.FleetManagementUserID != nil {
		in, out := &in.FleetManagementUserID, &out.FleetManagementUserID
		*out = new(int64)
		**out = **in
	}
	if in.GrafanasIPAllowListCname != nil {
		in, out := &in.GrafanasIPAllowListCname, &out.GrafanasIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.GraphiteIPAllowListCname != nil {
		in, out := &in.GraphiteIPAllowListCname, &out.GraphiteIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.GraphiteName != nil {
		in, out := &in.GraphiteName, &out.GraphiteName
		*out = new(string)
		**out = **in
	}
	if in.GraphitePrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.GraphitePrivateConnectivityInfoAvailabilityZoneIDs, &out.GraphitePrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GraphitePrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.GraphitePrivateConnectivityInfoAvailabilityZones, &out.GraphitePrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GraphitePrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.GraphitePrivateConnectivityInfoPrivateDNS, &out.GraphitePrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.GraphitePrivateConnectivityInfoRegions != nil {
		in, out := &in.GraphitePrivateConnectivityInfoRegions, &out.GraphitePrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GraphitePrivateConnectivityInfoServiceName != nil {
		in, out := &in.GraphitePrivateConnectivityInfoServiceName, &out.GraphitePrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.GraphiteStatus != nil {
		in, out := &in.GraphiteStatus, &out.GraphiteStatus
		*out = new(string)
		**out = **in
	}
	if in.GraphiteURL != nil {
		in, out := &in.GraphiteURL, &out.GraphiteURL
		*out = new(string)
		**out = **in
	}
	if in.GraphiteUserID != nil {
		in, out := &in.GraphiteUserID, &out.GraphiteUserID
		*out = new(int64)
		**out = **in
	}
	if in.InfluxURL != nil {
		in, out := &in.InfluxURL, &out.InfluxURL
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LogsIPAllowListCname != nil {
		in, out := &in.LogsIPAllowListCname, &out.LogsIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.LogsName != nil {
		in, out := &in.LogsName, &out.LogsName
		*out = new(string)
		**out = **in
	}
	if in.LogsPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.LogsPrivateConnectivityInfoAvailabilityZoneIDs, &out.LogsPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogsPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.LogsPrivateConnectivityInfoAvailabilityZones, &out.LogsPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogsPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.LogsPrivateConnectivityInfoPrivateDNS, &out.LogsPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.LogsPrivateConnectivityInfoRegions != nil {
		in, out := &in.LogsPrivateConnectivityInfoRegions, &out.LogsPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogsPrivateConnectivityInfoServiceName != nil {
		in, out := &in.LogsPrivateConnectivityInfoServiceName, &out.LogsPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.LogsStatus != nil {
		in, out := &in.LogsStatus, &out.LogsStatus
		*out = new(string)
		**out = **in
	}
	if in.LogsURL != nil {
		in, out := &in.LogsURL, &out.LogsURL
		*out = new(string)
		**out = **in
	}
	if in.LogsUserID != nil {
		in, out := &in.LogsUserID, &out.LogsUserID
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OncallAPIURL != nil {
		in, out := &in.OncallAPIURL, &out.OncallAPIURL
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(int64)
		**out = **in
	}
	if in.OrgName != nil {
		in, out := &in.OrgName, &out.OrgName
		*out = new(string)
		**out = **in
	}
	if in.OrgSlug != nil {
		in, out := &in.OrgSlug, &out.OrgSlug
		*out = new(string)
		**out = **in
	}
	if in.OtlpPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.OtlpPrivateConnectivityInfoAvailabilityZoneIDs, &out.OtlpPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OtlpPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.OtlpPrivateConnectivityInfoAvailabilityZones, &out.OtlpPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OtlpPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.OtlpPrivateConnectivityInfoPrivateDNS, &out.OtlpPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.OtlpPrivateConnectivityInfoRegions != nil {
		in, out := &in.OtlpPrivateConnectivityInfoRegions, &out.OtlpPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OtlpPrivateConnectivityInfoServiceName != nil {
		in, out := &in.OtlpPrivateConnectivityInfoServiceName, &out.OtlpPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.OtlpURL != nil {
		in, out := &in.OtlpURL, &out.OtlpURL
		*out = new(string)
		**out = **in
	}
	if in.PdcAPIPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.PdcAPIPrivateConnectivityInfoAvailabilityZoneIDs, &out.PdcAPIPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcAPIPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.PdcAPIPrivateConnectivityInfoAvailabilityZones, &out.PdcAPIPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcAPIPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.PdcAPIPrivateConnectivityInfoPrivateDNS, &out.PdcAPIPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.PdcAPIPrivateConnectivityInfoRegions != nil {
		in, out := &in.PdcAPIPrivateConnectivityInfoRegions, &out.PdcAPIPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcAPIPrivateConnectivityInfoServiceName != nil {
		in, out := &in.PdcAPIPrivateConnectivityInfoServiceName, &out.PdcAPIPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.PdcGatewayPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.PdcGatewayPrivateConnectivityInfoAvailabilityZoneIDs, &out.PdcGatewayPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcGatewayPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.PdcGatewayPrivateConnectivityInfoAvailabilityZones, &out.PdcGatewayPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcGatewayPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.PdcGatewayPrivateConnectivityInfoPrivateDNS, &out.PdcGatewayPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.PdcGatewayPrivateConnectivityInfoRegions != nil {
		in, out := &in.PdcGatewayPrivateConnectivityInfoRegions, &out.PdcGatewayPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PdcGatewayPrivateConnectivityInfoServiceName != nil {
		in, out := &in.PdcGatewayPrivateConnectivityInfoServiceName, &out.PdcGatewayPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.ProfilesIPAllowListCname != nil {
		in, out := &in.ProfilesIPAllowListCname, &out.ProfilesIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.ProfilesName != nil {
		in, out := &in.ProfilesName, &out.ProfilesName
		*out = new(string)
		**out = **in
	}
	if in.ProfilesPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.ProfilesPrivateConnectivityInfoAvailabilityZoneIDs, &out.ProfilesPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProfilesPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.ProfilesPrivateConnectivityInfoAvailabilityZones, &out.ProfilesPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProfilesPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.ProfilesPrivateConnectivityInfoPrivateDNS, &out.ProfilesPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.ProfilesPrivateConnectivityInfoRegions != nil {
		in, out := &in.ProfilesPrivateConnectivityInfoRegions, &out.ProfilesPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProfilesPrivateConnectivityInfoServiceName != nil {
		in, out := &in.ProfilesPrivateConnectivityInfoServiceName, &out.ProfilesPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.ProfilesStatus != nil {
		in, out := &in.ProfilesStatus, &out.ProfilesStatus
		*out = new(string)
		**out = **in
	}
	if in.ProfilesURL != nil {
		in, out := &in.ProfilesURL, &out.ProfilesURL
		*out = new(string)
		**out = **in
	}
	if in.ProfilesUserID != nil {
		in, out := &in.ProfilesUserID, &out.ProfilesUserID
		*out = new(int64)
		**out = **in
	}
	if in.PrometheusIPAllowListCname != nil {
		in, out := &in.PrometheusIPAllowListCname, &out.PrometheusIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.PrometheusName != nil {
		in, out := &in.PrometheusName, &out.PrometheusName
		*out = new(string)
		**out = **in
	}
	if in.PrometheusPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.PrometheusPrivateConnectivityInfoAvailabilityZoneIDs, &out.PrometheusPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrometheusPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.PrometheusPrivateConnectivityInfoAvailabilityZones, &out.PrometheusPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrometheusPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.PrometheusPrivateConnectivityInfoPrivateDNS, &out.PrometheusPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.PrometheusPrivateConnectivityInfoRegions != nil {
		in, out := &in.PrometheusPrivateConnectivityInfoRegions, &out.PrometheusPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrometheusPrivateConnectivityInfoServiceName != nil {
		in, out := &in.PrometheusPrivateConnectivityInfoServiceName, &out.PrometheusPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.PrometheusRemoteEndpoint != nil {
		in, out := &in.PrometheusRemoteEndpoint, &out.PrometheusRemoteEndpoint
		*out = new(string)
		**out = **in
	}
	if in.PrometheusRemoteWriteEndpoint != nil {
		in, out := &in.PrometheusRemoteWriteEndpoint, &out.PrometheusRemoteWriteEndpoint
		*out = new(string)
		**out = **in
	}
	if in.PrometheusStatus != nil {
		in, out := &in.PrometheusStatus, &out.PrometheusStatus
		*out = new(string)
		**out = **in
	}
	if in.PrometheusURL != nil {
		in, out := &in.PrometheusURL, &out.PrometheusURL
		*out = new(string)
		**out = **in
	}
	if in.PrometheusUserID != nil {
		in, out := &in.PrometheusUserID, &out.PrometheusUserID
		*out = new(int64)
		**out = **in
	}
	if in.RegionSlug != nil {
		in, out := &in.RegionSlug, &out.RegionSlug
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.TracesIPAllowListCname != nil {
		in, out := &in.TracesIPAllowListCname, &out.TracesIPAllowListCname
		*out = new(string)
		**out = **in
	}
	if in.TracesName != nil {
		in, out := &in.TracesName, &out.TracesName
		*out = new(string)
		**out = **in
	}
	if in.TracesPrivateConnectivityInfoAvailabilityZoneIDs != nil {
		in, out := &in.TracesPrivateConnectivityInfoAvailabilityZoneIDs, &out.TracesPrivateConnectivityInfoAvailabilityZoneIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TracesPrivateConnectivityInfoAvailabilityZones != nil {
		in, out := &in.TracesPrivateConnectivityInfoAvailabilityZones, &out.TracesPrivateConnectivityInfoAvailabilityZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TracesPrivateConnectivityInfoPrivateDNS != nil {
		in, out := &in.TracesPrivateConnectivityInfoPrivateDNS, &out.TracesPrivateConnectivityInfoPrivateDNS
		*out = new(string)
		**out = **in
	}
	if in.TracesPrivateConnectivityInfoRegions != nil {
		in, out := &in.TracesPrivateConnectivityInfoRegions, &out.TracesPrivateConnectivityInfoRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TracesPrivateConnectivityInfoServiceName != nil {
		in, out := &in.TracesPrivateConnectivityInfoServiceName, &out.TracesPrivateConnectivityInfoServiceName
		*out = new(string)
		**out = **in
	}
	if in.TracesStatus != nil {
		in, out := &in.TracesStatus, &out.TracesStatus
		*out = new(string)
		**out = **in
	}
	if in.TracesURL != nil {
		in, out := &in.TracesURL, &out.TracesURL
		*out = new(string)
		**out = **in
	}
	if in.TracesUserID != nil {
		in, out := &in.TracesUserID, &out.TracesUserID
		*out = new(int64)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackObservation.
func (in *StackObservation) DeepCopy() *StackObservation {
	if in == nil {
		return nil
	}
	out := new(StackObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackParameters) DeepCopyInto(out *StackParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackParameters.
func (in *StackParameters) DeepCopy() *StackParameters {
	if in == nil {
		return nil
	}
	out := new(StackParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackSpec) DeepCopyInto(out *StackSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackSpec.
func (in *StackSpec) DeepCopy() *StackSpec {
	if in == nil {
		return nil
	}
	out := new(StackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackStatus) DeepCopyInto(out *StackStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackStatus.
func (in *StackStatus) DeepCopy() *StackStatus {
	if in == nil {
		return nil
	}
	out := new(StackStatus)
	in.DeepCopyInto(out)
	return out
}
