/*
Copyright 2026 Grafana Labs
*/

// Code generated by generate-observed; DO NOT EDIT.

package v1alpha1

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// OrganizationParameters defines the input parameters for the grafana_cloud_organization data source.
type OrganizationParameters struct {
	// The organization slug.
	// +optional
	Slug *string `json:"slug,omitempty"`
}

// OrganizationObservation holds the observed (computed) fields from the grafana_cloud_organization data source.
type OrganizationObservation struct {
	// The date and time the organization was created.
	CreatedAt *string `json:"createdAt,omitempty"`

	// The organization name.
	Name *string `json:"name,omitempty"`

	// The organization slug.
	Slug *string `json:"slug,omitempty"`

	// The date and time the organization was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty"`

	// The organization URL.
	URL *string `json:"url,omitempty"`
}

type OrganizationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationParameters `json:"forProvider"`
}

type OrganizationStatus struct {
	xpv1.ResourceStatus `json:",inline"`
	AtProvider          OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories=crossplane
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"

// Organization is an observe-only resource backed by the grafana_cloud_organization Terraform data source.
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organization.
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

var Organization_GroupVersionKind = schema.GroupVersionKind{
	Group:   CRDGroup,
	Version: CRDVersion,
	Kind:    "Organization",
}

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
