name: Releases

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - run: ./hack/merge-crds.sh
    - uses: ncipollo/release-action@1c89adf39833729d8f85a31ccbc451b078733c80 # v1.19.1
      with:
        allowUpdates: true
        artifacts: "dist/*"
        body: "See https://marketplace.upbound.io/providers/grafana/provider-grafana/ for API documentation."
