name: Releases

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - run: ./hack/merge-crds.sh
    - uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
      with:
        allowUpdates: true
        artifacts: "dist/*"
        body: "See https://marketplace.upbound.io/providers/grafana/provider-grafana/ for API documentation."
