apiVersion: slo.grafana.crossplane.io/v1alpha1
kind: SLO
metadata:
  annotations:
    meta.upbound.io/example-id: slo/v1alpha1/slo
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    alerting:
    - fastburn:
      - annotation:
        - key: name
          value: SLO Burn Rate Very High
        - key: description
          value: Error budget is burning too fast
      slowburn:
      - annotation:
        - key: name
          value: SLO Burn Rate High
        - key: description
          value: Error budget is burning too fast
    description: Terraform Description
    destinationDatasource:
    - selector:
        matchLabels:
          testing.upbound.io/example-name: example
    label:
    - key: slo
      value: terraform
    name: Terraform Testing
    objectives:
    - value: 0.995
      window: 30d
    query:
    - freeform:
      - query: sum(rate(apiserver_request_total{code!="500"}[$__rate_interval])) /
          sum(rate(apiserver_request_total[$__rate_interval]))
      type: freeform
