apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: AccessPolicyRotatingToken
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/accesspolicyrotatingtoken
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessPolicyId: ${grafana_cloud_access_policy.test.policy_id}
    displayName: My Policy Rotating Token
    earlyRotationWindow: 24h
    expireAfter: 720h
    namePrefix: my-policy-rotating-token
    region: prod-us-east-0

---

apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: AccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/accesspolicyrotatingtoken
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    displayName: My Policy
    name: my-policy
    realm:
    - labelPolicy:
      - selector: '{namespace="default"}'
      stackSelector:
        matchLabels:
          testing.upbound.io/example-name: grafana_cloud_organization
      type: org
    region: prod-us-east-0
    scopes:
    - metrics:read
    - logs:read
