apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: ComponentV1Alpha1
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/componentv1alpha1
  labels:
    testing.upbound.io/example-name: payments
  name: payments
spec:
  forProvider:
    metadata:
      uid: payments-api
    spec:
      title: Payments API

---

apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/componentv1alpha1
  labels:
    testing.upbound.io/example-name: checkout
  name: checkout
spec:
  forProvider:
    name: Checkout Team
