apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: StackServiceAccountRotatingToken
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/stackserviceaccountrotatingtoken
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    earlyRotationWindowSeconds: 604800
    namePrefix: key_foo
    secondsToLive: 7776000
    serviceAccountId: ${grafana_cloud_stack_service_account.cloud_sa.id}
    stackSlug: <your stack slug>

---

apiVersion: cloud.grafana.crossplane.io/v1alpha1
kind: StackServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/stackserviceaccountrotatingtoken
  labels:
    testing.upbound.io/example-name: cloud_sa
  name: cloud-sa
spec:
  forProvider:
    cloudStackSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    isDisabled: false
    name: cloud service account
    role: Admin
